name: Poao frontend container dev

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/poao-frontend-container-dev.yaml"
      - ".nais/nais-dev.yaml"
  workflow_dispatch:

concurrency:
  group: poao_frontend_container_dev
  cancel-in-progress: true

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # ratchet:actions/checkout@v5
      - name: deploy gcp dev
        uses: nais/deploy/actions/deploy@961addd1e4d4211f1a7333ada5fde85f7c9aa5b7 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais-dev.yaml
